baseURL: 'https://mikestaszel.com/'
languageCode: 'en-us'
title: 'Mike Staszel'
theme: 'PaperMod'

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: resume
      name: resume
      url: https://storage.googleapis.com/mkst/resume/mike-resume.pdf
      weight: 20

permalinks:
  posts: /:year/:month/:day/:title/

params:
  author: 'Mike Staszel'

  homeInfoParams:
    Title: 'Hi there 👋'
    Content: "I'm a software engineer, blockchain enthusiast, occasional blogger."

  socialIcons:
    - name: 'github'
      url: 'https://github.com/mk6502/'
    - name: 'linkedin'
      url: 'https://www.linkedin.com/in/mikestaszel/'
    - name: 'medium'
      url: 'https://medium.com/@mkstz'
    - name: 'twitter'
      url: 'https://twitter.com/mk312x'
    - name: 'stackoverflow'
      url: 'https://stackoverflow.com/users/1591438/mikestaszel'
    - name: 'cv'
      url: 'https://storage.googleapis.com/mkst/resume/mike-resume.pdf'
    - name: 'email'
      url: 'mailto:mike@sent.fm'
    - name: 'rss'
      url: '/index.xml'

  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  defaultTheme: 'dark'
  disableThemeToggle: true
