baseURL: 'https://mikestaszel.com/'
languageCode: 'en-us'
title: 'Mike Staszel'
theme: 'PaperMod'
enableRobotsTXT: true

menu:
  main:
    - identifier: 'github'
      name: ''
      pre: "<i class='fa fa-github'></i>"
      url: 'https://github.com/mk6502/'
      weight: 10
    - identifier: 'linkedin'
      name: ''
      pre: "<i class='fa fa-linkedin-square'></i>"
      url: 'https://www.linkedin.com/in/mikestaszel/'
      weight: 20
    - identifier: blog
      name: 'Blog'
      url: '/posts/'
      weight: 30
    - identifier: resume
      name: Resume
      url: https://storage.googleapis.com/mkst/resume/mike-resume.pdf
      weight: 40

permalinks:
  posts: /:year/:month/:day/:title/

params:
  author: 'Mike Staszel'
  description: "I'm a software engineer, blockchain enthusiast, and occasional blogger."

  homeInfoParams:
    Title: "Hi there, I'm Mike 👋"
    Content: "I'm a software engineer, blockchain enthusiast, and occasional blogger."

  socialIcons:
    - name: 'github'
      url: 'https://github.com/mk6502/'
    - name: 'linkedin'
      url: 'https://www.linkedin.com/in/mikestaszel/'
    - name: 'medium'
      url: 'https://medium.com/@mkstz'
    - name: 'twitter'
      url: 'https://twitter.com/mk312x'
    - name: 'stackoverflow'
      url: 'https://stackoverflow.com/users/1591438/mikestaszel'
    - name: 'cv'
      url: 'https://storage.googleapis.com/mkst/resume/mike-resume.pdf'
    - name: 'email'
      url: 'mailto:mike@mikestaszel.com'
    - name: 'rss'
      url: '/index.xml'

  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  defaultTheme: 'dark'
  disableThemeToggle: true

sitemap:
  changefreq: "weekly"
  filename: "sitemap.xml"
  priority: 0.5
