baseURL: 'https://mikestaszel.com/'
languageCode: 'en-us'
title: 'Mike Staszel'
theme: 'PaperMod'

permalinks:
  posts: /:year/:month/:day/:title/

params:
  author: 'Mike Staszel'

  homeInfoParams:
    Title: 'Hi there 👋'
    Content: "I'm a software engineer, blockchain enthusiast, occasional blogger."

  socialIcons:
    - name: 'linkedin'
      url: 'https://www.linkedin.com/in/mikestaszel/'
    - name: 'github'
      url: 'https://github.com/mk6502/'
    - name: 'twitter'
      url: 'https://twitter.com/mk312x'
    - name: 'cv'
      url: 'https://storage.googleapis.com/mkst/resume/mike-resume.pdf'
    - name: 'email'
      url: 'mailto:mike@sent.fm'

  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  defaultTheme: 'dark'
  disableThemeToggle: true
